steps:
- name: python
  entrypoint: pip
  args: ["install", "-r", "requirements.txt", "--user"]
- name: python
  entrypoint: python
  args:
  - 'setup.py'
  - 'sdist'
- name: python
  entrypoint: python
  args:
  - '-m'
  - 'twine'
  - 'upload'
  - '--repository-url'
  - 'https:///us-east1-python.pkg.dev/rohankhurana-test-project/my-repo/'
  - 'dist/*'
  - '--verbose'
- name: python
  entrypoint: pip
  args:
  - 'install'
  - '--index-url'
  - 'https://us-east1-python.pkg.dev/rohankhurana-test-project/my-repo/'
  - 'acme.sql'
  - '--verbose'
