steps:
- name: python
  entrypoint: pip
  args: ["install", "keyrings.google-artifactregistry-auth", "twine", "--user"]
- name: python
  entrypoint: python
  args:
  - 'python-example-flask/setup.py'
  - 'sdist'
- name: python
  entrypoint: python
  args:
  - '-m'
  - 'twine'
  - 'upload'
  - '--repository-url'
  - 'https://us-east1-python.pkg.dev/rohankhurana-test-project/my-repo/'
  - 'dist/*'
  - '--verbose'
- name: python
  entrypoint: pip
  args:
  - 'install'
  - '--index-url'
  - 'https://us-east1-python.pkg.dev/rohankhurana-test-project/my-repo/'
  - 'acme.sql'
  - '--verbose'
options:
  logging: CLOUD_LOGGING_ONLY
